config/routes.rb
Rails.application.routes.draw do
  mount Api => '/'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :users, only: [:update] do
    collection do
      get :me
    end
  end

  devise_for :users
  root to: 'home#index'

  resources :products do
    resources :comments
    resources :images
    resources :likes, only: [] do
      collection do
        put :like
        put :unlike
      end
    end
  end

  # get '/products', to: 'products#index', as: 'products'
  # get '/products/new', to: 'products#new', as: 'new_product'
  # get '/products/:id', to: 'products#show', as: 'product'
  # post '/products', to: 'products#create', as: 'create_product'
  # delete '/products/:id', to: 'products#destroy', as: 'destroy_product'
  #
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product'
  # patch '/products/:id', to: 'products#update', as: 'update_product'
  #
  # resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  include Likable
  include Redis::Objects
  counter :view

  serialize :like, Array

  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :uniq_commented_users, -> { uniq },
           through: :comments, source: :user

  has_many :images, as: :imagable, inverse_of: :imagable

  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, :price, presence: true
  validates_uniqueness_of :name

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :destroy, :edit, :update]
  before_action :increment_prod, only: :show

	def index
    @q = Product.ransack(params[:q])
    @products = @q.result.order('updated_at DESC')

    # @per_page = params[:per_page].present? ? params[:per_page].to_i : 5
    @page = params[:page].present? ? params[:page].to_i : 1

    @products = @products.page(@page)
    respond_to do |format|
      format.html
      format.json { render :index }
    end
	end

	def show
  end

  def new
    @product = Product.new
  end

  def create
    Product.create(product_params)

    redirect_to products_path
  end

  def destroy
    @product.destroy
    if request.xhr?
      head :no_content
    else
      redirect_to products_path
    end
  end

  def edit
  end

  def update
    @product.update_attributes(product_params)

    redirect_to products_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, images_attributes: [:file])
  end

  def increment_prod
    @product.view.increment
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def price_format(value)
    "#{value} $"
  end
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.text_field :price, placeholder: 'Price' %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.file_field :images %>

  <%= f.submit 'Create' %>
<% end %>

app/views/products/_image_fields.html.erb
<div class="nested-fields">
  <%= f.file_field :file %>
  <%= f.hidden_field :_destroy, class: '_destroy' %>
  <br>
  <%= image_tag(f.object.file_url, width: '100') if f.object.file.present? %>
  <a href="#" class="remove-image">remove image</a>
</div>

app/views/products/edit.html.erb
<br />
<%= form_for @product do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :price, placeholder: 'Price' %>

  <%= f.submit 'Save' %>
<% end %>
<%= link_to 'New image', new_product_image_path(@product) %>

app/views/products/index.html.erb
<p></p>



<div class="products__view">
  <main role="main">
    <div class="jumbotron">
      <div class="col-sm-8 mx-auto">
        <h1>Products List</h1>
        <div class="product__list">

          <%= search_form_for @q do |f| %>
            <%= f.search_field :name_cont, placeholder: 'Search by name' %>
            <br>
            <%= f.search_field :price_gteq, placeholder: 'Min price' %>
            <br>
            <%= f.search_field :price_lteq, placeholder: 'Max price' %>
            <br>
            <%= f.submit 'Search', class: 'btn btn-default' %>
          <% end %>

          <ul>
            <% @products.each do |product| %>
              <li>
                <%= link_to product.name, product_path(id: product.id) %>
                <%= price_format (product.price) %> |
                views:  <%= product.view.value %> |
                comments: <%= product.comments_count %> |
                likes: <%= product.likes.count %> |
                <% if product.liked?(current_user) %>
                  <%= link_to 'Unlike', unlike_product_likes_path(product), method: :put, remote: true %>
                <% else %>
                  <%= link_to 'Like', like_product_likes_path(product), method: :put, remote: true %>
                <% end %> |

                <%= link_to 'Edit', edit_product_path(id: product.id) %> |
                <%= link_to 'Delete', product_path(id: product.id), method: :delete %>

                <!--Another delete method-->
                <!--<%= form_for product, method: :delete do |f| %>-->
                  <!--<% f.submit 'Delete' %>-->
                  <!--<% end %>-->
              </li>
            <% end %>
          </ul>

          <%= paginate @products, :theme => 'twitter-bootstrap-4' %>

        </div>
        <div class="active">
          <p>
            <a class="btn btn-primary" href="<%= new_product_path %>" role="button">NEW PRODUCT &raquo;</a>
          </p>
        </div>

      </div>
    </div>
  </main>
</div>

app/views/products/new.html.erb
<br />
<%= form_for @product do |f| %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.text_field :price, placeholder: 'Price' %>

  <%= f.submit 'Save' %>
<% end %>

app/views/products/show.html.erb
<br />
<h1>
	<%= @product.name %>:
	<%= @product.price %> $
</h1>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <% @product.images.each_with_index do |image, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <%= image_tag(image.file_url, class: 'd-block w-100') %>
        <!--<img class="d-block w-100" src="..." alt="First slide">-->
      </div>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<p><%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %></p>
<br />
<p><%= link_to 'Show comments', product_comments_path(@product) %></p>